module.exports = {
    varationAvailable: "<VAR>",
    emotions: "<EMO>",
    negativeEmotions: "<NEM>",
    positiveEmotions: "<PEM>",
    lovehearts: "<LOV>",
    humans: "<HUM>",
    groupsOfPeople: "<GRO>",
    actionsAndBodyParts: "<ACT>",
    animals: "<ANI>",
    plants: "<PLA>",
    creatures: "<CRE>",
    food: "<FOO>",
    drinks: "<DRI>",
    sportsAndActivities: "<SPO>",
    transportation: "<TRA>",
    locations: "<LOC>",
    countryFlags: "<COU>",
    weather: "<WEA>",
    astronomical: "<AST>",
    symbols: "<SYM>",
    objects: "<OBJ>",
    time: "<TIM>"
};